[package]
name = "rusty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# libc = "0.2"

[lib]
name = "rusty"
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.24.3"