[package]
name = "mti"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
microfft = "0.5.0"
micromath = "2.0.0"
dsp = "0.10.2"